name = "CavityEquilibria"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DrWatson = "2.19.1"
julia = "1.12.3"
